#!/usr/bin/env python3
"""Regenerates lib/services/processing/hans_hant_table.dart from the vendored
OpenCC character dictionaries (tool/l10n/opencc/{ST,TS}Characters.txt,
Apache-2.0 — see LICENCE.md).

Char-level, 1:1 codepoint-aligned by construction (§13 wave 2 / D8): word
boundaries and timings survive conversion exactly. Multi-value entries keep
OpenCC's first (most frequent) variant; identity mappings are dropped.

  python3 tool/l10n/gen_hans_hant.py
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "tool" / "l10n" / "opencc"
OUT = ROOT / "lib" / "services" / "processing" / "hans_hant_table.dart"


def load(name: str) -> dict[str, str]:
    table = {}
    for line in (SRC / name).read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        key, _, values = line.partition("\t")
        value = values.split(" ")[0]
        if key and value and key != value:
            table[key] = value
    return table


def dart_map(name: str, table: dict[str, str], doc: str) -> str:
    pairs = [f"'{k}': '{v}'" for k, v in sorted(table.items())]
    lines, line = [], "  "
    for pair in pairs:
        entry = pair + ", "
        if len(line) + len(entry) > 78:
            lines.append(line.rstrip())
            line = "  "
        line += entry
    if line.strip():
        lines.append(line.rstrip())
    body = "\n".join(lines)
    return f"{doc}\nconst {name} = <String, String>{{\n{body}\n}};\n"


def main() -> None:
    s2t = load("STCharacters.txt")
    t2s = load("TSCharacters.txt")
    OUT.write_text(
        "// GENERATED by tool/l10n/gen_hans_hant.py — do not edit by hand.\n"
        "// Source: OpenCC character dictionaries (Apache-2.0), vendored at\n"
        "// tool/l10n/opencc/. Char-level, first (most frequent) variant only\n"
        "// — phrase-level distinctions are a documented v1 limitation (§13).\n"
        "\n"
        + dart_map(
            "simplifiedToTraditional",
            s2t,
            "/// Simplified → Traditional, one codepoint to one codepoint.",
        )
        + "\n"
        + dart_map(
            "traditionalToSimplified",
            t2s,
            "/// Traditional → Simplified, one codepoint to one codepoint.",
        ),
        encoding="utf-8",
    )
    print(f"wrote {OUT} ({len(s2t)} s2t, {len(t2s)} t2s entries)")


if __name__ == "__main__":
    main()
