/* Diktafon's C shim over llama.cpp (§6.3, D3).
 *
 * Dart binds only this API. Like dk_whisper it is deliberately tiny and
 * flat: no llama structs cross the FFI boundary, chat templating happens
 * here (the model's own template via llama_chat_apply_template), and
 * cancellation is a caller-owned int32 flag polled during decode.
 *
 * Thread-safety: one dk_llama must be used from one thread at a time
 * (Diktafon runs it inside a single worker isolate; queue concurrency is 1).
 */
#pragma once

#include <stdint.h>

#if defined(_WIN32)
#define DK_EXPORT __declspec(dllexport)
#else
#define DK_EXPORT __attribute__((visibility("default")))
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct dk_llama dk_llama;

/* Loads a GGUF model and creates a context of n_ctx tokens.
 * Returns NULL on failure. */
DK_EXPORT dk_llama * dk_llama_init(const char * model_path,
                                   int32_t n_ctx,
                                   int32_t n_threads);
DK_EXPORT void dk_llama_free(dk_llama * dl);

/* Runs one [system, user] chat exchange and stores the assistant reply.
 * temperature <= 0 selects greedy (deterministic) sampling.
 * cancel  optional flag; set *cancel to non-zero to abort mid-decode.
 * Returns 0 on success (also when aborted — caller checks its own flag),
 * -1 on template/tokenize failure, -2 on decode failure, -3 when the
 * prompt does not fit the context window (caller truncates its input). */
DK_EXPORT int32_t dk_llama_generate(dk_llama * dl,
                                    const char * system_prompt,
                                    const char * user_prompt,
                                    int32_t max_tokens,
                                    float temperature,
                                    const int32_t * cancel);

/* The reply generated by the last successful dk_llama_generate — valid
 * until the next generate/free. UTF-8, NUL-terminated. */
DK_EXPORT const char * dk_llama_result(dk_llama * dl);

#ifdef __cplusplus
}
#endif
